spring:
  application:
    name: spring-boot-admin-client-two

server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    show-details: always

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true
