spring:
  application:
    name: spring-boot-admin-client
  boot:
    admin:
      client:
        username: admin
        password: admin
        url: http://localhost:8080

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    show-details: always
