server:
  port: 8765

spring:
  application:
    name: spring-boot-admin-server
  boot:
    admin:
      discovery:
        ignored-services: spring-boot-admin-server
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      instance:
        preferIpAddress: true
  instance:
    hostname: localhost
